petstore.baseUrl=https://petstore.swagger.io/v2/
timeout=30000
username=admin
password=password123
chatGptUrl=https://api.openai.com/v1/chat/completions
geminiAppUrl=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent

